export const CATEROGY_LIST_REQUEST = "CATEROGY_LIST_REQUEST"
export const CATEROGY_LIST_SUCCESS = "CATEROGY_LIST_SUCCESS"
export const CATEROGY_LIST_FAIL = "CATEROGY_LIST_FAIL"

export const CATEROGY_DELETE_REQUEST = "CATEROGY_DELETE_REQUEST"
export const CATEROGY_DELETE_SUCCESS = "CATEROGY_DELETE_SUCCESS"
export const CATEROGY_DELETE_FAIL = "CATEROGY_DELETE_FAIL"

export const CATEROGY_CREATE_REQUEST = "CATEROGY_CREATE_REQUEST"
export const CATEROGY_CREATE_SUCCESS = "CATEROGY_CREATE_SUCCESS"
export const CATEROGY_CREATE_FAIL = "CATEROGY_CREATE_FAIL"
export const CATEROGY_CREATE_RESET = "CATEROGY_CREATE_RESET"

export const CATEROGY_UPDATE_REQUEST = "CATEROGY_UPDATE_REQUEST"
export const CATEROGY_UPDATE_SUCCESS = "CATEROGY_UPDATE_SUCCESS"
export const CATEROGY_UPDATE_FAIL = "CATEROGY_UPDATE_FAIL"
export const CATEROGY_UPDATE_RESET = "CATEROGY_UPDATE_RESET"
